# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Driveshaft
tagline:          'Google Drive → JSON'
# description:      'Power your site with versioned JSON from Google Drive documents'
url:              https://newsdev.github.io/driveshaft
baseurl:          /driveshaft/
basepath:         /driveshaft
page_order:
  - index.md
  - authentication.md
  - s3.md
  - heroku.md
  - reference.md
logo:             public/img/logo.png

analytics:
  tracking_id:    'UA-7885722-43'

authors:
  -
    name:           'Michael Strickland'
    url:            https://twitter.com/moriogawa
  # -
  #   name:           'TK'
  #   url:            https://twitter.com/TK

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/newsdev/driveshaft
